const markers = () => {
 return {
  "Argentina": {coordinates: [-60, -30], size: '8', text: 'Argentina'},
  "Brazil": {coordinates: [-55, -10], size: '10', text: 'Brazil'},
  "Mexico": {coordinates: [-102, 23], size: '8', text: 'Mexico'},
  "Colombia": { coordinates: [-74, 4], size: '6', text: 'Colombia' },
  "Venezuela": { coordinates: [-66, 8], size: '6', text: 'Venezuela' },
  "Peru": { coordinates: [-76, -10], size: '6', text: 'Peru' },
  "Chile": { coordinates: [-71, -35], size: '6', text: 'Chile' },
  "Ecuador": { coordinates: [-78, -2], size: '6', text: 'Ecuador' },
  "Bolivia": { coordinates: [-65, -17], size: '6', text: 'Bolivia' },
  "Paraguay": { coordinates: [-58, -23], size: '6', text: 'Paraguay' },
  "Uruguay": { coordinates: [-56, -33], size: '6', text: 'Uruguay' },
  "Guyana": { coordinates: [-58, 5], size: '6', text: 'Guyana' },
  "Canada": { coordinates: [-106, 55], size: '8', text: 'Canada' },
  "United States": { coordinates: [-98, 38], size: '10', text: 'United States' },
  "Russia": { coordinates: [105, 60], size: '8', text: 'Russia' },
  "Mongolia": { coordinates: [105, 46], size: '6', text: 'Mongolia' },
  "Australia": { coordinates: [133, -27], size: '10', text: 'Australia' },
  "Libya": { coordinates: [17, 26], size: '6', text: 'Libya' },
  "Algeria": { coordinates: [2, 28], size: '6', text: 'Algeria' },
  "Democratic Republic of the Congo": { coordinates: [23, -3], size: '6', text: 'DRC' },
  "Mali": { coordinates: [-2, 17], size: '6', text: 'Mali' },
  "Angola": { coordinates: [17, -12], size: '6', text: 'Angola' },
  "Japan": { coordinates: [138, 40], size: '6', text: 'Japan' },
  "Iran": { coordinates: [54, 32], size: '6', text: 'Iran' },
  "Iraq": { coordinates: [44, 33], size: '6', text: 'Iraq' },
  "Pakistan": { coordinates: [70, 30], size: '6', text: 'Pakistan' },
  "India": { coordinates: [78, 23], size: '9', text: 'India' },
  "Madagascar": { coordinates: [47, -19], size: '6', text: 'Madagascar' },
  "Sudan": { coordinates: [30, 15], size: '6', text: 'Sudan' },
  "Egypt": { coordinates: [31, 26], size: '6', text: 'Egypt' },
  "Saudi Arabia": { coordinates: [45, 24], size: '6', text: 'Saudi Arabia' },
  "Oman": { coordinates: [57, 21], size: '6', text: 'Oman' },
  "Yemen": { coordinates: [48, 15], size: '6', text: 'Yemen' },
  "Ukraine": { coordinates: [31, 49], size: '6', text: 'Ukraine' },
  "Turkey": { coordinates: [35, 39], size: '6', text: 'Turkey' },
  "Kazakhstan": { coordinates: [68, 48], size: '6', text: 'Kazakhstan' },
  "New Zealand": { coordinates: [174, -40], size: '6', text: 'New Zealand' },
  "Indonesia": { coordinates: [117, -2], size: '6', text: 'Indonesia' },
  "Norway": { coordinates: [15, 64], size: '6', text: 'Norway' },
  "Chad": { coordinates: [18, 15], size: '6', text: 'Chad' },
  "Ethiopia": { coordinates: [40, 9], size: '6', text: 'Ethiopia' },
  "Somalia": { coordinates: [46, 6], size: '6', text: 'Somalia' },
  "South Africa": { coordinates: [24, -30], size: '6', text: 'South Africa' },
  "Zimbabwe": { coordinates: [30, -20], size: '6', text: 'Zimbabwe' },
  "Kenya": { coordinates: [38, 1], size: '6', text: 'Kenya' },
  "Tanzania": { coordinates: [35, -6], size: '6', text: 'Tanzania' },
  "Zambia": { coordinates: [28, -15], size: '6', text: 'Zambia' },
  "Nigeria": { coordinates: [8, 10], size: '6', text: 'Nigeria' },
  "Niger": { coordinates: [9, 17], size: '6', text: 'Niger' },
  "Myanmar": { coordinates: [96, 21], size: '6', text: 'Myanmar' },
  "Philippines": { coordinates: [122, 13], size: '6', text: 'Philippines' },
  "Malaysia": { coordinates: [112, 4], size: '6', text: 'Malaysia' },
  "Sri Lanka": { coordinates: [81, 7], size: '6', text: 'Sri Lanka' },
  "Cameroon": { coordinates: [12, 4], size: '6', text: 'Cameroon' },
  "Namibia": { coordinates: [17, -25], size: '6', text: 'Namibia' },
  "Botswana": { coordinates: [24, -22], size: '6', text: 'Botswana' },
  "Tunisia": { coordinates: [9, 34], size: '6', text: 'Tunisia' },
  "Morocco": { coordinates: [-7, 32], size: '6', text: 'Morocco' },
  "Spain": { coordinates: [-4, 40], size: '6', text: 'Spain' },
  "France": { coordinates: [3, 46], size: '6', text: 'France' },
  "United Kingdom": { coordinates: [-2, 54], size: '6', text: 'UK' },
  "Ireland": { coordinates: [-8, 51], size: '6', text: 'Ireland' },
  "Iceland": { coordinates: [-18, 64], size: '6', text: 'Iceland' },
  "Turkmenistan": { coordinates: [60, 38], size: '6', text: 'Turkmenistan' },
  "Nepal": { coordinates: [84, 28], size: '6', text: 'Nepal' },
  "China": { coordinates: [104, 35], size: '10', text: 'China' },
  "Thailand": { coordinates: [101, 15], size: '6', text: 'Thailand' },
  "South Korea": { coordinates: [128, 36], size: '6', text: 'South Korea' },
  "Belarus": { coordinates: [28, 53], size: '6', text: 'Belarus' },
  "Visited and has album": {coordinates: [-130, -10], size: '15', text: 'Visited and has album', color: "#5d954a"},
  "Visited, no album": {coordinates: [-130, -20], size: '15', text: 'Visited, no album', color: "#c5efb7"}
 }
}

export default markers;
