const markers = () => {
 return [
  {text: 'Argentina', coordinates: [-60, -30], size: '8'},
  {text: 'Brazil', coordinates: [-55, -10], size: '10'},
  {text: 'Mexico', coordinates: [-102, 23], size: '8'},
  {text: 'Colombia', coordinates: [-74, 4], size: '6'},
  {text: 'Venezuela', coordinates: [-66, 8], size: '6'},
  {text: 'Peru', coordinates: [-76, -10], size: '6'},
  {text: 'Chile', coordinates: [-71, -35], size: '6'},
  {text: 'Ecuador', coordinates: [-78, -2], size: '6'},
  {text: 'Bolivia', coordinates: [-65, -17], size: '6'},
  {text: 'Paraguay', coordinates: [-58, -23], size: '6'},
  {text: 'Uruguay', coordinates: [-56, -33], size: '6'},
  {text: 'Guyana', coordinates: [-58, 5], size: '6'},
  {text: 'Canada', coordinates: [-106, 55], size: '10'},
  {text: 'United States', coordinates: [-98, 38], size: '10'},
  {text: 'Russia', coordinates: [105, 60], size: '8'},
  {text: 'Mongolia', coordinates: [105, 46], size: '6'},
  {text: 'Australia', coordinates: [133, -27], size: '10'},
  {text: 'Libya', coordinates: [17, 26], size: '6'},
  {text: 'Algeria', coordinates: [2, 28], size: '6'},
  {text: 'DRC', coordinates: [23, -3], size: '6'},
  {text: 'Mali', coordinates: [-2, 17], size: '6'},
  {text: 'Angola', coordinates: [17, -12], size: '6'},
  {text: 'Japan', coordinates: [138, 40], size: '6'},
  {text: 'Iran', coordinates: [54, 32], size: '6'},
  {text: 'Iraq', coordinates: [44, 33], size: '6'},
  {text: 'Pakistan', coordinates: [70, 30], size: '6'},
  {text: 'India', coordinates: [78, 23], size: '9'},
  {text: 'Madagascar', coordinates: [47, -19], size: '6'},
  {text: 'Sudan', coordinates: [30, 15], size: '6'},
  {text: 'Egypt', coordinates: [31, 26], size: '6'},
  {text: 'Saudi Arabia', coordinates: [45, 24], size: '6'},
  {text: 'Oman', coordinates: [57, 21], size: '6'},
  {text: 'Yemen', coordinates: [48, 15], size: '6'},
  {text: 'Ukraine', coordinates: [31, 49], size: '6'},
  {text: 'Turkey', coordinates: [35, 39], size: '6'},
  {text: 'Kazakhstan', coordinates: [68, 48], size: '6'},
  {text: 'New Zealand', coordinates: [174, -40], size: '6'},
  {text: 'Indonesia', coordinates: [117, -2], size: '6'},
  {text: 'Norway', coordinates: [12, 64], size: '6'},
  {text: 'Chad', coordinates: [18, 15], size: '6'},
  {text: 'Ethiopia', coordinates: [40, 9], size: '6'},
  {text: 'Somalia', coordinates: [46, 6], size: '6'},
  {text: 'South Africa', coordinates: [24, -30], size: '6'},
  {text: 'Zimbabwe', coordinates: [30, -20], size: '6'},
  {text: 'Kenya', coordinates: [38, 1], size: '6'},
  {text: 'Tanzania', coordinates: [35, -6], size: '6'},
  {text: 'Mozambique', coordinates: [42, -13], size: '6'},
  {text: 'Zambia', coordinates: [28, -15], size: '6'},
  {text: 'Nigeria', coordinates: [8, 10], size: '6'},
  {text: 'Niger', coordinates: [9, 17], size: '6'},
  {text: 'Myanmar', coordinates: [96, 21], size: '6'},
  {text: 'Philippines', coordinates: [122, 13], size: '6'},
  {text: 'Malaysia', coordinates: [112, 4], size: '6'},
  {text: 'Sri Lanka', coordinates: [81, 7], size: '6'},
  {text: 'Cameroon', coordinates: [12, 4], size: '6'},
  {text: 'Namibia', coordinates: [17, -25], size: '6'},
  {text: 'Botswana', coordinates: [24, -22], size: '6'},
  {text: 'Tunisia', coordinates: [9, 34], size: '6'},
  {text: 'Morocco', coordinates: [-7, 32], size: '6'},
  {text: 'Spain', coordinates: [-4, 40], size: '6'},
  {text: 'France', coordinates: [3, 46], size: '6'},
  {text: 'UK', coordinates: [-2, 54], size: '6'},
  {text: 'Ireland', coordinates: [-8, 51], size: '6'},
  {text: 'Iceland', coordinates: [-18, 64], size: '5'},
  {text: 'Turkmenistan', coordinates: [60, 38], size: '6'},
  {text: 'Nepal', coordinates: [84, 28], size: '6'},
  {text: 'China', coordinates: [104, 35], size: '10'},
  {text: 'Thailand', coordinates: [101, 15], size: '6'},
  {text: 'South Korea', coordinates: [128, 36], size: '6'},
  {text: 'Belarus', coordinates: [28, 53], size: '6'},
  {text: 'Visited and has album', coordinates: [-130, -10], size: '15', color: "#5d954a"},
  {text: 'Visited, no album', coordinates: [-130, -20], size: '15', color: "#c5efb7"}
]


}

export default markers;
